name: Name Printer

description: Name Printer

inputs:
  firstname:
    description: First
    required: true
    default: 'denice'
  lastname:
    description: Last
    required: true
    default: 'dopes'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.firstname }}
    - ${{ inputs.lastname}}

  
