name: Prisma Image Review

description: Builds and scans docker images from main branch and PR branch to look for diff.

inputs:
  primsa_access_key_id:
    description: Prisma Cloud Access Key ID
    required: true
  primsa_access_key_secret:
    description: Prisma Cloud Access Key Secret
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.primsa_access_key_id }}
    - ${{ inputs.primsa_access_key_secret}}
  env:
    TWISTLOCK_USER="${{ inputs.primsa_access_key_id }}"
    TWISTLOCK_PASSWORD="${{ inputs.primsa_access_key_id }}"

  
