name: Prisma Image Review

description: Builds and scans docker images from main branch and PR branch to look for diff.

inputs:
  prisma_access_key_id:
    description: Prisma Cloud Access Key ID
    required: true
  prisma_access_key_secret:
    description: Prisma Cloud Access Key Secret
    required: true
  prisma_console_url:
    description: Prisma Cloud Console URL
    required: true
  prisma_api_version:
    description: Prisma Cloud API Version
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    TWISTLOCK_USER: ${{ inputs.prisma_access_key_id }}
    TWISTLOCK_PASSWORD: ${{ inputs.prisma_access_key_secret }}
    CONSOLE_URL: ${{ inputs.prisma_console_url }}
    API_VERSION: ${{ inputs.prisma_api_version }}

  
